### ISSUE TITLE
values only pull in whole digit 

### ISSUE THREAD

**Issue by apU823** [jweier/SolarDataParser#6]
in tesla app, values seem to be available in decimal points.  is it possible to extra at that level or just limited to extract whole digit only

**Comment by jweier** [comment]
I updated the two charts to show two digits. To update your code grab the latests scripts.js file from the assets folder and rerun main.py.

**Comment by apU823** [comment]
tried the above but still getting values in whole digits in scripts.js file and also still showing as 2 digit in graph

**Comment by apU823** [comment]
output from terminal:

Lifetime Net Energy: 0
Lifetime Net Energy Value: 0
Lifetime Solar Energy Created: 745
Lifetime Solar Energy Created Value: 231
Daily Average Electricity Usage: 15.21
Daily Average Electricity Produced from Solar: 15.21
var timestamp = ['03-01-2023', '03-02-2023', '03-03-2023', '03-04-2023', '03-05-2023', '01-16-2023', '01-17-2023', '01-18-2023', '01-19-2023', '01-20-2023', '01-21-2023', '01-22-2023', '01-23-2023', '01-24-2023', '01-25-2023', '01-26-2023', '01-27-2023', '01-28-2023', '01-29-2023', '01-30-2023', '01-31-2023', '02-01-2023', '02-02-2023', '02-03-2023', '02-04-2023', '02-05-2023', '02-06-2023', '02-07-2023', '02-08-2023', '02-09-2023', '02-10-2023', '02-11-2023', '02-12-2023', '02-13-2023', '02-14-2023', '02-15-2023', '02-16-2023', '02-17-2023', '02-18-2023', '02-19-2023', '02-20-2023', '02-21-2023', '02-22-2023', '02-23-2023', '02-24-2023', '02-25-2023', '02-26-2023', '02-27-2023', '02-28-2023']
var solar_energy_exported = [6, 25, 12, 14, 16, 7, 21, 6, 13, 1, 11, 7, 7, 5, 19, 1, 10, 12, 15, 6, 16, 5, 22, 22, 23, 23, 16, 14, 15, 23, 8, 24, 25, 10, 24, 26, 23, 10, 3, 28, 19, 17, 11, 7, 11, 27, 14, 20, 25]
var grid_energy_imported = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
var grid_energy_exported_from_solar = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
var consumer_energy_imported_from_grid = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
var consumer_energy_imported_from_solar = [6, 25, 12, 14, 16, 7, 21, 6, 13, 1, 11, 7, 7, 5, 19, 1, 10, 12, 15, 6, 16, 5, 22, 22, 23, 23, 16, 14, 15, 23, 8, 24, 25, 10, 24, 26, 23, 10, 3, 28, 19, 17, 11, 7, 11, 27, 14, 20, 25]
var net_energy = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
var consumer_energy_imported_from_everywhere = [6, 25, 12, 14, 16, 7, 21, 6, 13, 1, 11, 7, 7, 5, 19, 1, 10, 12, 15, 6, 16, 5, 22, 22, 23, 23, 16, 14, 15, 23, 8, 24, 25, 10, 24, 26, 23, 10, 3, 28, 19, 17, 11, 7, 11, 27, 14, 20, 25]

**Comment by jweier** [comment]
Hey - Sorry, I forgot I changed something else as well. Gran main.py and the scripts.js that I just pushed. You should see the raw data and the chart switch to 2 decimal places.

**Comment by apU823** [comment]
main.py did not push it seems.  

git still says it was updated 2 days ago
